version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: "16:00"
    groups:
      actions:
        update-types:
          - patch
          - minor
          - major

  - package-ecosystem: gomod
    directories:
      - /lib/*
      - /runtime
      - /runtime/languages/golang/testdata
      - /sdk/go
      - /sdk/go/examples/*
      - /sdk/go/templates/*
    schedule:
      interval: weekly
      day: wednesday
      time: "16:00"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    versioning-strategy: increase
    directories:
      - /cli
      - /runtime/explorer/content
      - /runtime/languages/assemblyscript/testdata
      - /sdk/assemblyscript/src
      - /sdk/assemblyscript/examples/*
      - /sdk/assemblyscript/templates/*
      - /tools/release-info
    schedule:
      interval: weekly
      day: wednesday
      time: "16:00"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
    ignore:
      # We target Node.js 22
      - dependency-name: "@types/node"
        versions: [">= 23.0.0"]
