version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/runtime"
      - "/runtime/languages/golang/testdata"
      - "/sdk/go"
      - "/sdk/go/examples/*"
      - "/sdk/go/tools/modus-go-build"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "16:00"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "16:00"
    groups:
      actions:
        update-types:
          - "patch"
          - "minor"
          - "major"
