# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
project_name: runtime
monorepo:
  tag_prefix: runtime/
  dir: runtime
git:
  tag_sort: -version:creatordate
  prerelease_suffix: "-"
before:
  hooks:
    - sh -c "cd runtime && go mod tidy"
builds:
  - main: .
    binary: modus_runtime
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s
      - -w
      - -X github.com/hypermodeinc/modus/runtime/config.version={{.Version}}
      - >-
        {{- if eq .Os "windows"}}
          -checklinkname=0
        {{- end }}

# temporarily disabled
# notarize:
#   macos:
#     - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
#       sign:
#         certificate: "{{.Env.MACOS_SIGN_P12}}"
#         password: "{{.Env.MACOS_SIGN_PASSWORD}}"
#       notarize:
#         issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
#         key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
#         key: "{{.Env.MACOS_NOTARY_KEY}}"

archives:
  - files:
      - ../README.md
      - ../LICENSE
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: ["tar.gz"]
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: ["zip"]
checksum:
  name_template: checksums.txt
release:
  prerelease: auto
changelog:
  # TODO: decide how to generate changelog
  disable: true
