services:
 
  db:
    image: postgres
    restart: always
    expose:
      - 5433
    ports:
      - 5433:5433
    environment:
      POSTGRES_DB: my-runtime-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata1:/var/lib/postgresql/data1
    command: -p 5433

  redis:
    image: redislabs/redisearch:latest
    container_name: "redis-server"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-net

volumes:
  pgdata1:
  redis-data:

networks:
  redis-net:
