// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: hm.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HMType int32

const (
	HMType_VOID   HMType = 0 // return only
	HMType_INT    HMType = 1 // signed int32
	HMType_FLOAT  HMType = 2 // signed float32
	HMType_STRING HMType = 3
	HMType_BOOL   HMType = 4
)

// Enum value maps for HMType.
var (
	HMType_name = map[int32]string{
		0: "VOID",
		1: "INT",
		2: "FLOAT",
		3: "STRING",
		4: "BOOL",
	}
	HMType_value = map[string]int32{
		"VOID":   0,
		"INT":    1,
		"FLOAT":  2,
		"STRING": 3,
		"BOOL":   4,
	}
)

func (x HMType) Enum() *HMType {
	p := new(HMType)
	*p = x
	return p
}

func (x HMType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HMType) Descriptor() protoreflect.EnumDescriptor {
	return file_hm_proto_enumTypes[0].Descriptor()
}

func (HMType) Type() protoreflect.EnumType {
	return &file_hm_proto_enumTypes[0]
}

func (x HMType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HMType.Descriptor instead.
func (HMType) EnumDescriptor() ([]byte, []int) {
	return file_hm_proto_rawDescGZIP(), []int{0}
}

type HMFunction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resolver string `protobuf:"bytes,1,opt,name=resolver,proto3" json:"resolver,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// note: this cannot be a map<string, HMType>, because we need to preserve order
	Parameters []*HMParameter `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty"`
	ReturnType HMType         `protobuf:"varint,4,opt,name=returnType,proto3,enum=HMType" json:"returnType,omitempty"`
}

func (x *HMFunction) Reset() {
	*x = HMFunction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HMFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HMFunction) ProtoMessage() {}

func (x *HMFunction) ProtoReflect() protoreflect.Message {
	mi := &file_hm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HMFunction.ProtoReflect.Descriptor instead.
func (*HMFunction) Descriptor() ([]byte, []int) {
	return file_hm_proto_rawDescGZIP(), []int{0}
}

func (x *HMFunction) GetResolver() string {
	if x != nil {
		return x.Resolver
	}
	return ""
}

func (x *HMFunction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HMFunction) GetParameters() []*HMParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *HMFunction) GetReturnType() HMType {
	if x != nil {
		return x.ReturnType
	}
	return HMType_VOID
}

type HMParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type HMType `protobuf:"varint,2,opt,name=type,proto3,enum=HMType" json:"type,omitempty"`
}

func (x *HMParameter) Reset() {
	*x = HMParameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HMParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HMParameter) ProtoMessage() {}

func (x *HMParameter) ProtoReflect() protoreflect.Message {
	mi := &file_hm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HMParameter.ProtoReflect.Descriptor instead.
func (*HMParameter) Descriptor() ([]byte, []int) {
	return file_hm_proto_rawDescGZIP(), []int{1}
}

func (x *HMParameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HMParameter) GetType() HMType {
	if x != nil {
		return x.Type
	}
	return HMType_VOID
}

var File_hm_proto protoreflect.FileDescriptor

var file_hm_proto_rawDesc = []byte{
	0x0a, 0x08, 0x68, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x93, 0x01, 0x0a, 0x0a, 0x48,
	0x4d, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x6f, 0x6c, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73,
	0x6f, 0x6c, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x0a, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x48, 0x4d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x0a, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x27, 0x0a, 0x0a, 0x72, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x48, 0x4d,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x3e, 0x0a, 0x0b, 0x48, 0x4d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x07, 0x2e, 0x48, 0x4d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x2a, 0x3c, 0x0a, 0x06, 0x48, 0x4d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x56, 0x4f,
	0x49, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x09, 0x0a,
	0x05, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49,
	0x4e, 0x47, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f, 0x4f, 0x4c, 0x10, 0x04, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hm_proto_rawDescOnce sync.Once
	file_hm_proto_rawDescData = file_hm_proto_rawDesc
)

func file_hm_proto_rawDescGZIP() []byte {
	file_hm_proto_rawDescOnce.Do(func() {
		file_hm_proto_rawDescData = protoimpl.X.CompressGZIP(file_hm_proto_rawDescData)
	})
	return file_hm_proto_rawDescData
}

var file_hm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hm_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hm_proto_goTypes = []interface{}{
	(HMType)(0),         // 0: HMType
	(*HMFunction)(nil),  // 1: HMFunction
	(*HMParameter)(nil), // 2: HMParameter
}
var file_hm_proto_depIdxs = []int32{
	2, // 0: HMFunction.parameters:type_name -> HMParameter
	0, // 1: HMFunction.returnType:type_name -> HMType
	0, // 2: HMParameter.type:type_name -> HMType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_hm_proto_init() }
func file_hm_proto_init() {
	if File_hm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HMFunction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HMParameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hm_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hm_proto_goTypes,
		DependencyIndexes: file_hm_proto_depIdxs,
		EnumInfos:         file_hm_proto_enumTypes,
		MessageInfos:      file_hm_proto_msgTypes,
	}.Build()
	File_hm_proto = out.File
	file_hm_proto_rawDesc = nil
	file_hm_proto_goTypes = nil
	file_hm_proto_depIdxs = nil
}
