version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: increase
    directories:
      - "/src"
      - "/examples/*"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "16:00"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "xid-ts"
        versions: ["1.1.3"] # see https://github.com/hypermodeinc/functions-as/pull/189

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "16:00"
    groups:
      actions:
        update-types:
          - "patch"
          - "minor"
          - "major"
