/*
 * Copyright 2024 Hypermode Inc.
 * Licensed under the terms of the Apache License, Version 2.0
 * See the LICENSE file that accompanied this code for further details.
 *
 * SPDX-FileCopyrightText: 2024 Hypermode Inc. <hello@hypermode.com>
 * SPDX-License-Identifier: Apache-2.0
 */

package main

import (
	"log"
	"os"
	"os/exec"
	"strings"
)

func main() {

	var version = getVersion()
	var content = `//
// ** THIS FILE IS AUTOGENERATED - DO NOT EDIT **
//
// The version number is the output from the command "git describe --tags --always".
// It will either be the exact tag name (ex., "v1.2.3"), or the tag name followed by
// the number of commits since the tag and the short commit hash (ex., "v1.2.3-7-g0f2b19e").
//

package config

const version = "` + version + `"
`
	_ = os.WriteFile("./config/version_generated.go", []byte(content), 0644)
}

func getVersion() string {

	// If the environment variable is set at build time, use it.
	// This is primarily for the docker build.
	v := os.Getenv("MODUS_BUILD_VERSION")
	if v != "" {
		return v
	}

	// Otherwise, get a version based on the git tag and commit hash.
	result, err := exec.Command("git", "describe", "--tags", "--always").Output()
	if err != nil {
		log.Fatal(err)
	}
	return strings.TrimSpace(string(result))
}
