//
// ** THIS FILE IS AUTOGENERATED - DO NOT EDIT **
// Instead, run 'go generate' in the root of the repository.
// It is also generated when launching from VSCode.
//
// The version number is the output from the command "git describe --tags --always".
// It will either be the exact tag name (ex., "v1.2.3"), or the tag name followed by
// the number of commits since the tag and the short commit hash (ex., "v1.2.3-7-g0f2b19e").
//

package config

const version = "v0.12.6-6-g51abf59"

