// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { HMType } from "./HMType";

export class HMParameter {
  static encode(message: HMParameter, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.name);

    writer.uint32(16);
    writer.int32(message.type);
  }

  static decode(reader: Reader, length: i32): HMParameter {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new HMParameter();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.name = reader.string();
          break;

        case 2:
          message.type = reader.int32();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  name: string;
  type: HMType;

  constructor(name: string = "", type: HMType = 0) {
    this.name = name;
    this.type = type;
  }
}
