// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

export enum HMType {
  VOID = 0,
  INT = 1,
  FLOAT = 2,
  STRING = 3,
  BOOL = 4,
}
