// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

export enum HMType {
  VOID = 0,
  BOOL = 1,
  INT = 2,
  FLOAT = 3,
  STRING = 4,
  JSON = 5,
}
