name: ci-golang-tests
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
jobs:
  golang-tests:
    name: test
    runs-on: warp-ubuntu-latest-x64-4x
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - name: Generate Code
        run: go generate ./...
      - name: Run Unit Tests
        run: |
          go install github.com/jstemmer/go-junit-report/v2@latest
          go test -v -race 2>&1 ./... | go-junit-report -set-exit-code > report.xml
      - name: Generate Test Summary
        if: always()
        uses: test-summary/action@v2
        with:
          paths: "report.xml"
