name: ci-golang-integration-tests
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
jobs:
  golang-tests:
    name: test
    runs-on: warp-ubuntu-latest-x64-4x
    if: github.event.pull_request.draft == false
    defaults:
      run:
        working-directory: runtime
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Generate Code
        run: go generate ./...
      - name: Run Integration Tests
        run: |
          go install github.com/jstemmer/go-junit-report/v2@latest
          go test -tags integration -v -race 2>&1 ./integration_tests/... | go-junit-report -set-exit-code -iocopy -out report.xml
      - name: Generate Test Summary
        if: always()
        uses: test-summary/action@v2
        with:
          paths: "runtime/report.xml"
