name: ci-golang-unit-tests
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
jobs:
  golang-tests:
    name: test
    runs-on: warp-ubuntu-latest-x64-4x
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache-dependency-path: runtime/go.sum
      - name: Run Unit Tests
        working-directory: runtime
        run: make test-ci
      - name: Generate Test Summary
        if: always()
        uses: test-summary/action@v2
        with:
          paths: "runtime/report.xml"
