# This workflow will lint all NPM-based projects in the repository that have a "lint" script defined in their package.json file.
name: ci-npm-lint
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
jobs:
  get-dirs:
    if: github.event_name == 'pull_request'
    name: find lintable npm projects
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.get-dirs.outputs.dirs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Search for package.json files with a lint script
        id: get-dirs
        run: echo "dirs=$(find . -name 'package.json' ! -path '*node_modules*' -exec sh -c 'jq -e ".scripts.lint" {} > /dev/null && dirname {}' \; | jq -Rsc 'split("\n")[:-1]')" >> ${GITHUB_OUTPUT}

  npm-lint:
    needs: get-dirs
    if: github.event_name == 'pull_request'
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{ fromJson(needs.get-dirs.outputs.dirs) }}
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ">=20"
      - name: Install dependencies
        run: npm install
      - name: Check code formatting (if configured)
        run: |
          if jq -e '.scripts["pretty:check"]' package.json > /dev/null; then
            npm run pretty:check
          else
            echo "Prettier not configured, skipping..."
          fi
      - name: Run the lint script
        run: npm run lint
