name: ci-release-info-lint
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - 'tools/release-info/**'
jobs:
  lint:
    if: github.event_name == 'pull_request'
    name: lint (tools/release-info)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tools/release-info
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ">=22"
      - name: Install dependencies
        run: npm ci
      - name: Check formatting
        run: npm run pretty:check
      - name: Lint
        run: npm run lint
