name: ci-runtime-integration-tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - runtime/**

permissions:
  contents: read
  actions: write

jobs:
  runtime-integration-tests:
    name: test (runtime)
    runs-on: warp-ubuntu-latest-x64-4x
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache-dependency-path: runtime/go.sum
      - name: Run Integration Tests
        working-directory: runtime
        run: make test-integration-ci
      - name: Generate Test Summary
        if: always()
        uses: test-summary/action@v2
        with:
          paths: runtime/report.xml
