name: Build Runtime

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - .github/workflows/ci-runtime-build.yml
      - runtime/**/*.go
      - runtime/go.mod
      - runtime/go.sum

permissions:
  contents: read

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on:
      "${{ matrix.os == 'linux' && 'warp-ubuntu-latest-x64-4x' || matrix.os == 'macos' &&
      'warp-macos-15-arm64-6x' || 'warp-windows-latest-x64-4x' }}"

    strategy:
      fail-fast: false
      matrix:
        os: [linux, macos, windows]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
          cache-dependency-path: runtime/go.sum
      - name: Build Runtime
        working-directory: runtime
        run: go build ${{ matrix.os == 'windows' && '-ldflags "-checklinkname=0"' || '' }}
